### ISSUE TITLE
Custom element doesn't exist: calcio-live-team-matches

### ISSUE THREAD

**Issue by amastrogiacomo1968** [Bobsilvio/calcio-live-card#3]
Buongiorno e grazie da subito per l'ottimo lavoro.
Sto provando a configurare la Squadra Card calcio-live-team-matches utilizzando il sensor della squadra che funziona regolarmete (vedo tutti gli attributi della squadra), quando provo a creare la card utilizzando il codice riportato di seguito ho l'errore "Custom element doesn't exist: calcio-live-team-matches."

```
type: custom:calcio-live-team-matches
entity: sensor.calciolive_team_586_torino_fc
max_events_visible: 5
max_events_total: 10
show_finished_matches: true
```

**Comment by amastrogiacomo1968** [comment]
Bisognava solo attende un tempo molto più lungo (un'ora quasi) di quello che mi aspettassi

**Comment by Bobsilvio** [comment]
bastava un riavvio. Sembrava un problema di card non trovata..

**Comment by amastrogiacomo1968** [comment]
ho riavviato più volte ma senza esito ed invece dopo un pò la card ha funzionato
